apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: exec-on-host
  labels:
    app: exec-on-host
spec:
  selector:
    matchLabels:
      app: exec-on-host
  template:
    metadata:
      labels:
        app: exec-on-host
    spec:
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/jarvice-compute: "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/jarvice-compute
        operator: Exists
      containers:
      - name: exec-on-host
        image: ubuntu:20.04
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - /exec-on-host/exec-on-host.sh
        securityContext:
          privileged: true
        volumeMounts:
        - name: exec-on-host
          mountPath: /exec-on-host
        - name: hostfs
          mountPath: /host
      volumes:
      - name: exec-on-host
        configMap:
          name: exec-on-host
          optional: false
      - name: hostfs
        hostPath:
          path: /
